### PR TITLE
Feature/text input

### PR DESCRIPTION
**Pull request by terezka**
it need some improvement regarding the port handling.

`cd examples/`
`elm-make TextInputExample.elm --output elm.js`
`open index.html`

### CODE REVIEW

**Comment by terezka** [comment]
realized i forgot to change branch to the rating one... hope you will live

**Comment by terezka** [comment]
which means that this has updates to rating too

**Comment by ryyppy** [comment]
Hmm, I tried your make-command, but I still get the port error:

```
Port Error:

    No argument was given for the port named 'textFieldHeight' with type:

        Int

    You need to provide an initial value!

    Find out more about ports here <http://elm-lang.org/learn/Ports.elm>

Open the developer console for more details.
```

**Comment by ryyppy** [comment]
Also since there was no `examples/index.html` I instead executed `elm-make TextInputExample.elm --output index.html` ... maybe this is the problem?

**Comment by terezka** [comment]
I made it so you don't need to make a port anymore, nor use the elm-make command. It's not fully developed as of now, as it just uses another div, measures the hight of the field and uses that for the textarea, which has its issues.

**Pull request closed without merging**
